PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /PWEAVER/EFA_TRC-TRACKING_NO .
    FIELD /PWEAVER/EFA_TRC-LEAD_SHIP_NO .
    FIELD /PWEAVER/EFA_TRC-INVOICE_NO .
    FIELD /PWEAVER/EFA_TRC-ACCOUNT_NO .
    FIELD /PWEAVER/EFA_TRC-PLANT .
    FIELD /PWEAVER/EFA_TRC-INVOICE_DATE .
    FIELD /PWEAVER/EFA_TRC-CARRIER .
    FIELD /PWEAVER/EFA_TRC-LICENSE_NO .
    FIELD /PWEAVER/EFA_TRC-USERID .
    FIELD /PWEAVER/EFA_TRC-PASSWORD .
    FIELD /PWEAVER/EFA_TRC-TRANSACTION_DATE .
    FIELD /PWEAVER/EFA_TRC-PICKUP_DATE .
    FIELD /PWEAVER/EFA_TRC-POD_DATE .
    FIELD /PWEAVER/EFA_TRC-POD_TIME .
    FIELD /PWEAVER/EFA_TRC-POD_SIGNATURE .
    FIELD /PWEAVER/EFA_TRC-TRANSIT_TIME .
    FIELD /PWEAVER/EFA_TRC-EXP_DEL_DATE .
    FIELD /PWEAVER/EFA_TRC-LATE_DELIVERY .
    FIELD /PWEAVER/EFA_TRC-GSR_STATUS .
    FIELD /PWEAVER/EFA_TRC-GSR_DESCRIPTION .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD /PWEAVER/EFA_TRC-TRACKING_NO .
    FIELD /PWEAVER/EFA_TRC-LEAD_SHIP_NO .
    FIELD /PWEAVER/EFA_TRC-INVOICE_NO .
  module detail_pai.
 endchain.
