PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PWEAVER/EFA_TRC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PWEAVER/EFA_TRC-TRACKING_NO .
    FIELD /PWEAVER/EFA_TRC-LEAD_SHIP_NO .
    FIELD /PWEAVER/EFA_TRC-INVOICE_NO .
    FIELD /PWEAVER/EFA_TRC-ACCOUNT_NO .
    FIELD /PWEAVER/EFA_TRC-PLANT .
    FIELD /PWEAVER/EFA_TRC-CARRIER .
    FIELD /PWEAVER/EFA_TRC-LICENSE_NO .
    FIELD /PWEAVER/EFA_TRC-USERID .
    FIELD /PWEAVER/EFA_TRC-PASSWORD .
    FIELD /PWEAVER/EFA_TRC-POD_SIGNATURE .
    FIELD /PWEAVER/EFA_TRC-TRANSIT_TIME .
    FIELD /PWEAVER/EFA_TRC-LATE_DELIVERY .
    FIELD /PWEAVER/EFA_TRC-GSR_STATUS .
    FIELD /PWEAVER/EFA_TRC-GSR_DESCRIPTION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PWEAVER/EFA_TRC-TRACKING_NO .
    FIELD /PWEAVER/EFA_TRC-LEAD_SHIP_NO .
    FIELD /PWEAVER/EFA_TRC-INVOICE_NO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
