PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PWEAVER/EFA_FED CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PWEAVER/EFA_FED-EXP_GRD_TRCK_ID .
    FIELD /PWEAVER/EFA_FED-BILL_TO_ACC_NUM .
    FIELD /PWEAVER/EFA_FED-INVOICE_DATE .
    FIELD /PWEAVER/EFA_FED-STORE_ID .
    FIELD /PWEAVER/EFA_FED-PAYOR .
    FIELD /PWEAVER/EFA_FED-GRD_TRCK_ID .
    FIELD /PWEAVER/EFA_FED-SERVICE_TYPE .
    FIELD /PWEAVER/EFA_FED-GRND_SERVICE .
    FIELD /PWEAVER/EFA_FED-POD_SER_AREA_COD .
    FIELD /PWEAVER/EFA_FED-POD_SIGN_DESC .
    FIELD /PWEAVER/EFA_FED-RECIPEINT_NAME .
    FIELD /PWEAVER/EFA_FED-RECIPEINT_COMP .
    FIELD /PWEAVER/EFA_FED-RECP_ADDR_LINE1 .
    FIELD /PWEAVER/EFA_FED-RECP_ADDR_LINE2 .
    FIELD /PWEAVER/EFA_FED-RECIPIENT_CITY .
    FIELD /PWEAVER/EFA_FED-RECIPIENT_STATE .
    FIELD /PWEAVER/EFA_FED-REC_ZIP_CODE .
    FIELD /PWEAVER/EFA_FED-REC_COUNTRY .
    FIELD /PWEAVER/EFA_FED-SHIPPER_COMPANY .
    FIELD /PWEAVER/EFA_FED-SHIPPER_NAME .
    FIELD /PWEAVER/EFA_FED-SHIPPER_ADD_LIN1 .
    FIELD /PWEAVER/EFA_FED-SHIPPER_ADD_LIN2 .
    FIELD /PWEAVER/EFA_FED-SHIPPER_CITY .
    FIELD /PWEAVER/EFA_FED-SHIPPER_STATE .
    FIELD /PWEAVER/EFA_FED-SHIPPER_ZIP_CODE .
    FIELD /PWEAVER/EFA_FED-SHIPPER_COUNTRY .
    FIELD /PWEAVER/EFA_FED-ORG_CUST_REF .
    FIELD /PWEAVER/EFA_FED-ORG_REF_2 .
    FIELD /PWEAVER/EFA_FED-ORG_REF_3 .
    FIELD /PWEAVER/EFA_FED-ORG_DEP_REF_DESC .
    FIELD /PWEAVER/EFA_FED-UPD_CUST_REF .
    FIELD /PWEAVER/EFA_FED-UPD_REF_2 .
    FIELD /PWEAVER/EFA_FED-UPD_REF_3 .
    FIELD /PWEAVER/EFA_FED-ORG_DEPT_REF_DES .
    FIELD /PWEAVER/EFA_FED-UPD_DEPT_REF_DES .
    FIELD /PWEAVER/EFA_FED-ORG_REC_ADD_LN1 .
    FIELD /PWEAVER/EFA_FED-ORG_REC_ADD_LN2 .
    FIELD /PWEAVER/EFA_FED-ORG_RECP_CITY .
    FIELD /PWEAVER/EFA_FED-ORG_RECP_STATE .
    FIELD /PWEAVER/EFA_FED-ORG_RECP_ZIP_COD .
    FIELD /PWEAVER/EFA_FED-ORG_RECP_COUNTY .
    FIELD /PWEAVER/EFA_FED-ZONE_CODE .
    FIELD /PWEAVER/EFA_FED-ENTRY_NUMBER .
    FIELD /PWEAVER/EFA_FED-COMM_DESC .
    FIELD /PWEAVER/EFA_FED-COMM_CNTRY_CODE .
    FIELD /PWEAVER/EFA_FED-COMM_DESC_1 .
    FIELD /PWEAVER/EFA_FED-COMM_CNTRY_CODE1 .
    FIELD /PWEAVER/EFA_FED-COMM_DESC_2 .
    FIELD /PWEAVER/EFA_FED-COMM_CNTRY_CODE2 .
    FIELD /PWEAVER/EFA_FED-COMM_DESC_3 .
    FIELD /PWEAVER/EFA_FED-COMM_CNTRY_CODE3 .
    FIELD /PWEAVER/EFA_FED-GRDTRCKIDADDCORR .
    FIELD /PWEAVER/EFA_FED-GRDTRCKIDADDGRSS .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES1 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES2 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES3 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES4 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES5 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES6 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES7 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES8 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES9 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES10 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES11 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES12 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES13 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES14 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES15 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES16 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES17 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES18 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES19 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES20 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES21 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES22 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES23 .
    FIELD /PWEAVER/EFA_FED-TRK_ID_CHG_DES24 .
    FIELD /PWEAVER/EFA_FED-GRSFLAG .
    FIELD /PWEAVER/EFA_FED-GRS_DESC .
    FIELD /PWEAVER/EFA_FED-LOST_FLAG .
    FIELD /PWEAVER/EFA_FED-LOST_DESC .
    FIELD /PWEAVER/EFA_FED-DAM_FLAG .
    FIELD /PWEAVER/EFA_FED-DAM_DESC .
    FIELD /PWEAVER/EFA_FED-CUSTOMER_ID .
    FIELD /PWEAVER/EFA_FED-CARRIER .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PWEAVER/EFA_FED-EXP_GRD_TRCK_ID .
    FIELD /PWEAVER/EFA_FED-BILL_TO_ACC_NUM .
    FIELD /PWEAVER/EFA_FED-INVOICE_DATE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
