*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /PWEAVER/LEFA_TRCTOP.              " Global Data
  INCLUDE /PWEAVER/LEFA_TRCUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /PWEAVER/LEFA_TRCF00                    . " subprograms
  INCLUDE /PWEAVER/LEFA_TRCI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /PWEAVER/LEFA_TRCF...              " Subprograms
* INCLUDE /PWEAVER/LEFA_TRCO...              " PBO-Modules
* INCLUDE /PWEAVER/LEFA_TRCI...              " PAI-Modules
