PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PWEAVER/EFA_UPS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PWEAVER/EFA_UPS-COUNTER .
    FIELD /PWEAVER/EFA_UPS-LEAD_SHIP_NUMBER .
    FIELD /PWEAVER/EFA_UPS-VERSION .
    FIELD /PWEAVER/EFA_UPS-BILL_OPT_CODE .
    FIELD /PWEAVER/EFA_UPS-TRCK_NUM .
    FIELD /PWEAVER/EFA_UPS-CHRG_DESC .
    FIELD /PWEAVER/EFA_UPS-SENDER_NAME .
    FIELD /PWEAVER/EFA_UPS-SENDER_CMP_NAME .
    FIELD /PWEAVER/EFA_UPS-SENDER_ADDR_LIN1 .
    FIELD /PWEAVER/EFA_UPS-SENDER_ADDR_LIN2 .
    FIELD /PWEAVER/EFA_UPS-RECEIVER_NAME .
    FIELD /PWEAVER/EFA_UPS-RECEIVER_COMP_NM .
    FIELD /PWEAVER/EFA_UPS-REC_ADDR_LINE_1 .
    FIELD /PWEAVER/EFA_UPS-ENTRY_PORT .
    FIELD /PWEAVER/EFA_UPS-ENTRY_NUMBER .
    FIELD /PWEAVER/EFA_UPS-SHP_DESC .
    FIELD /PWEAVER/EFA_UPS-MST_WAYBIL_NUM .
    FIELD /PWEAVER/EFA_UPS-LN_ITEM_NUM .
    FIELD /PWEAVER/EFA_UPS-GOODS_DESC .
    FIELD /PWEAVER/EFA_UPS-ITEM_UOM .
    FIELD /PWEAVER/EFA_UPS-IMP_TAX_ID .
    FIELD /PWEAVER/EFA_UPS-DEC_NUM .
    FIELD /PWEAVER/EFA_UPS-CARR_NAM .
    FIELD /PWEAVER/EFA_UPS-CCCD_NUM .
    FIELD /PWEAVER/EFA_UPS-CYCLE_NUM .
    FIELD /PWEAVER/EFA_UPS-FRG_TRD_REF_NUM .
    FIELD /PWEAVER/EFA_UPS-JOB_NUM .
    FIELD /PWEAVER/EFA_UPS-TRAN_MODE .
    FIELD /PWEAVER/EFA_UPS-TAX_TYPE .
    FIELD /PWEAVER/EFA_UPS-TARIFF_CODE .
    FIELD /PWEAVER/EFA_UPS-TARIFF_RATE .
    FIELD /PWEAVER/EFA_UPS-TARIFF_TRT_NUM .
    FIELD /PWEAVER/EFA_UPS-CONTACT_NAME .
    FIELD /PWEAVER/EFA_UPS-CONTACT_NUM .
    FIELD /PWEAVER/EFA_UPS-DOC_TYPE .
    FIELD /PWEAVER/EFA_UPS-OFF_NUM .
    FIELD /PWEAVER/EFA_UPS-DOC_NUM .
    FIELD /PWEAVER/EFA_UPS-ORD_CNCL .
    FIELD /PWEAVER/EFA_UPS-ORD_CNTRY .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_1 .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_2 .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_3 .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_4 .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_5 .
    FIELD /PWEAVER/EFA_UPS-PAY_ROLE_CODE .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_7 .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_8 .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_9 .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_10 .
    FIELD /PWEAVER/EFA_UPS-MISC_LINE_11 .
    FIELD /PWEAVER/EFA_UPS-OTH_CUST_NUM_IND .
    FIELD /PWEAVER/EFA_UPS-OTH_CUST_NUM .
    FIELD /PWEAVER/EFA_UPS-OTH_CUST_NAME .
    FIELD /PWEAVER/EFA_UPS-PCKG_DIM_UOM .
    FIELD /PWEAVER/EFA_UPS-ORG_SHP_PKG_QTY .
    FIELD /PWEAVER/EFA_UPS-TAX_LAW_ART_NUM .
    FIELD /PWEAVER/EFA_UPS-ORG_TRACK_NUM .
    FIELD /PWEAVER/EFA_UPS-PLACE_HOLD_28 .
    FIELD /PWEAVER/EFA_UPS-PLACE_HOLD_29 .
    FIELD /PWEAVER/EFA_UPS-PLACE_HOLD_30 .
    FIELD /PWEAVER/EFA_UPS-PLACE_HOLD_31 .
    FIELD /PWEAVER/EFA_UPS-BOL_1 .
    FIELD /PWEAVER/EFA_UPS-BOL_2 .
    FIELD /PWEAVER/EFA_UPS-BOL_3 .
    FIELD /PWEAVER/EFA_UPS-BOL_4 .
    FIELD /PWEAVER/EFA_UPS-BOL_5 .
    FIELD /PWEAVER/EFA_UPS-PO_1 .
    FIELD /PWEAVER/EFA_UPS-PO_2 .
    FIELD /PWEAVER/EFA_UPS-PO_3 .
    FIELD /PWEAVER/EFA_UPS-PO_4 .
    FIELD /PWEAVER/EFA_UPS-PO_5 .
    FIELD /PWEAVER/EFA_UPS-PO_6 .
    FIELD /PWEAVER/EFA_UPS-PO_7 .
    FIELD /PWEAVER/EFA_UPS-PO_8 .
    FIELD /PWEAVER/EFA_UPS-PO_9 .
    FIELD /PWEAVER/EFA_UPS-PO_10 .
    FIELD /PWEAVER/EFA_UPS-NMFC .
    FIELD /PWEAVER/EFA_UPS-DET_CLASS .
    FIELD /PWEAVER/EFA_UPS-FRT_SEQ_NUM .
    FIELD /PWEAVER/EFA_UPS-DEC_FRT_CLS .
    FIELD /PWEAVER/EFA_UPS-PLACE_HOLD_34 .
    FIELD /PWEAVER/EFA_UPS-GSR_FLAG .
    FIELD /PWEAVER/EFA_UPS-GSR_DESC .
    FIELD /PWEAVER/EFA_UPS-LOST_FLAG .
    FIELD /PWEAVER/EFA_UPS-LOST_DESC .
    FIELD /PWEAVER/EFA_UPS-DAMAGE_FLAG .
    FIELD /PWEAVER/EFA_UPS-DAMAGE_DESC .
    FIELD /PWEAVER/EFA_UPS-CUSTOMER_ID .
    FIELD /PWEAVER/EFA_UPS-CHRG_DESC1 .
    FIELD /PWEAVER/EFA_UPS-CHRG_DESC2 .
    FIELD /PWEAVER/EFA_UPS-CHRG_DESC3 .
    FIELD /PWEAVER/EFA_UPS-CHRG_DESC4 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PWEAVER/EFA_UPS-COUNTER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
